development:
  :concurrency: 1 # те в девелопменте будет только 1 поток(1 параллельно выполняющаяся задача)
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 15 %> # в продакшене либо считаем значение переменной среды либо поставим 15
:queues:
  - default     # будет очередь выполнения с данным названием (можно создавать много очередей с разным приоритетом)
  - scheduler   # например доп очередь для гема sidekiq-scheduler (deploy)
:max_retries: 1 # сколько раз задача будет перевыполняться, при возникновении ошибок (по умолчанию 25)
