# # frozen_string_literal: true
#
# require 'rake'
# require 'rake/clean'
# require 'rspec/core/rake_task'
# require 'rubocop/rake_task'
#
# begin
#   require 'bundler/setup'
#   Bundler::GemHelper.install_tasks
# rescue LoadError
#   puts 'although not required, bundler is recommened for running the tests'
# end
#
# RSpec::Core::RakeTask.new(:spec)
#
# RuboCop::RakeTask.new do |task|
#   task.requires << 'rubocop-performance'
#   task.requires << 'rubocop-rspec'
# end
#
# # У каждой задачи Рэйк может быть пространство имен
# namespace :fun_translations do
#   CLOBBER.include(FileList['./*.gem'])
#
#   desc 'Updates RubyGems, installs dependencies'
#   task :install do
#     puts 'Running bundle install'
#     sh 'gem update --system' # вызов в терминале
#     sh 'bundle'
#   end
#
#   desc 'Builds the gem'
#   task :build do
#     puts 'Building'
#     sh 'gem build fun_translations.gemspec'
#   end
# end
#
# # Но можно запускать задачи и из глобального пространства имен
# task rubospec: %w[rubocop spec] # задача включает вызов рубокопа, а потом рспек, как будто пишем в терминале
#
# task full_build: %w[clobber fun_translations:install fun_translations:build]
#
# task default: :full_build
