CleanWorker:          # тут говорим какой воркер хотим использовать
  cron: "0 0 * * *"   # как часто эта задача должна выполняться(тут каждый день в 0 часов), эти настройки крон можно погуглить
  queue: scheduler    # название очереди которую испольщуем для этой задачи (тут scheduler) должна быть прописана и в sidekiq.yml естественно в списке очередей (queue)
