source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"



gem "rails", "~> 7.0.7"
# "~> 7.0.7"   -   эта тильда указывает на то что можно обновлять гем бандлером до любых версий подразделов(например тут: 7.0.9 или 7.1.5 итд), но не до новой основной версии(например тут 8.0.0), тоесть до нее он автоматически бандлером не обновится

gem "sprockets-rails"

gem "sqlite3", "~> 1.4"

gem "puma", "~> 5.0"

gem "jsbundling-rails"

gem "cssbundling-rails"

gem "jbuilder"

gem "tzinfo-data"

gem "bootsnap", require: false

gem 'faker', '~> 3'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
end
